using System;
using System.Collections.Generic;
using DataAccumulator.DataAccessLayer.Interfaces;
using DataAccumulator.Shared.Models;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Bson.Serialization.Options;

namespace DataAccumulator.DataAccessLayer.Entities
{
    public class CollectedData : IEntity
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // Id - CollectedData identification number
        [BsonRepresentation(BsonType.String)]
        public Guid Id { get; set; }
        // ClientId - Client identification number

        [BsonRepresentation(BsonType.String)]
        public Guid ClientId { get; set; }

        public CollectedDataType CollectedDataType { get; set; }

        public int ProcessesCount { get; set; }
        public List<ProcessData> Processes { get; set; }
        public float CpuUsagePercentage { get; set; }
        public float FreeRamMBytes { get; set; }
        public float TotalRamMBytes { get; set; }
        public float FreeRamPercentage { get; set; }
        public float InterruptsPerSeconds { get; set; }
        public float LocalDiskFreeMBytes { get; set; }
        public float LocalDiskTotalMBytes { get; set; }
        public float LocalDiskFreePercentage { get; set; }
        [BsonDateTimeOptions]
        public DateTime Time { get; set; }
    }
}
